# Generated by Django 6.0.4 on 2026-04-29 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_customerhealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='analytics.customer'),
        ),
    ]
