# Generated by Django 6.0.4 on 2026-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_usageevent_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerhealth",
            name="did_churn",
            field=models.BooleanField(default=False),
        ),
    ]
