# Generated by Django 6.0.4 on 2026-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_customerhealth_did_churn"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerhealth",
            name="ml_churn_probability",
            field=models.FloatField(default=0),
        ),
    ]
