# Generated by Django 6.0.4 on 2026-05-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_customerhealth_ml_churn_probability"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerHealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_score", models.FloatField(default=0)),
                ("feature_adoption_score", models.FloatField(default=0)),
                ("reliability_score", models.FloatField(default=0)),
                ("support_score", models.FloatField(default=0)),
                ("health_score", models.FloatField(default=0)),
                ("churn_risk", models.FloatField(default=0)),
                ("ml_churn_probability", models.FloatField(default=0)),
                ("risk_label", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="analytics.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
