# Generated by Django 6.0.4 on 2026-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_customerhealthsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(max_length=255)),
                ("events_created", models.PositiveIntegerField(default=0)),
                ("customers_created", models.PositiveIntegerField(default=0)),
                ("duplicates_skipped", models.PositiveIntegerField(default=0)),
                ("invalid_rows_skipped", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
