# Generated by Django 6.0.4 on 2026-04-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('installed_app', 'Installed App'), ('configured_app', 'Configured App'), ('created_clone', 'Created Clone'), ('used_dashboard_filter', 'Used Dashboard Filter'), ('connected_external_data_source', 'Connected External Data Source'), ('sync_failed', 'Sync Failed'), ('opened_support_ticket', 'Opened Support Ticket'), ('subscription_cancelled', 'Subscription Cancelled')], max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='analytics.customer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
