# Generated by Django 6.0.4 on 2026-04-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_score', models.FloatField(default=0)),
                ('feature_adoption_score', models.FloatField(default=0)),
                ('reliability_score', models.FloatField(default=0)),
                ('support_score', models.FloatField(default=0)),
                ('health_score', models.FloatField(default=0)),
                ('churn_risk', models.FloatField(default=0)),
                ('risk_label', models.CharField(choices=[('healthy', 'Healthy'), ('watch', 'Watch'), ('high_risk', 'High Risk')], default='watch', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='analytics.customer')),
            ],
            options={
                'ordering': ['-health_score'],
            },
        ),
    ]
